name: kernel_ls
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - fenics-dolfinx
  - mpich
  - pyvista
  - numpy
  - opt_einsum
  - scipy
  - tqdm
  - matplotlib
  - jupyter
  - ipython
  - gmsh
  - python-gmsh
  - jaxtyping
  - pytest
  - snakeviz
  - flake8
  - flake8-pyproject
  - black
  - pip:
    - flake8-docstrings
