[tool.black]
line-length = 120
target-version = ["py310", "py311", "py312"]

[tool.flake8]
ignore = [
    'E203',
    'E231',
    'E241',
    'E701',
    'E704',
    'F722',
    'W503'
]
per-file-ignores = [
    '__init__.py:F401',
]
max-line-length = 120
count = true
docstring-convention = "numpy"